# Based on the "trust" template v0.1.2
# https://github.com/japaric/trust/tree/v0.1.2

environment:
  global:
  # TODO This is the Rust channel that build jobs will use by default but can be
  # overridden on a case by case basis down below
    RUST_VERSION: stable

    # TODO Update this to match the name of your project.
    CRATE_NAME: alfred-pinboard-rs

  # TODO These are all the build jobs. Adjust as necessary. Comment out what you
  # don't need
  matrix:
    # MinGW
    # - TARGET: i686-pc-windows-gnu
    # - TARGET: x86_64-pc-windows-gnu

    # MSVC
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc
  RUST_BACKTRACE: 1
  alfred_debug: 1
  alfred_version: 4.0.1
  alfred_workflow_version: 0.11.1
  alfred_workflow_uid: hamid63
  alfred_workflow_name: RustyPin
  alfred_workflow_bundleid: 'cc.hamid.alfred-pinboard-rs'
  alfred_workflow_data: 'C:\projects\alfred-pinboard-rs'
  alfred_workflow_cache: 'C:\projects\alfred-pinboard-rs'


init:
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

install:
  - ps: >-
      If ($Env:TARGET -eq 'x86_64-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw64\bin'
      } ElseIf ($Env:TARGET -eq 'i686-pc-windows-gnu') {
        $Env:PATH += ';C:\msys64\mingw32\bin'
      }
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

# TODO This is the "test phase", tweak it as you see fit
test_script:
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build --target %TARGET% &&
      cargo run --target %TARGET% -- config --authorization hamid:12345 &&
      cargo run --target %TARGET% -- config -d &&
      cargo test --target %TARGET% -- --nocapture --test-threads=1
    )

cache:
  - C:\Users\appveyor\.cargo\registry
  - target

branches:
  only:
    - /^v?\d+\.\d+\.\d+.*$/
    - master

notifications:
  - provider: Email
    on_build_success: false

# Building is done in the test phase, so we disable Appveyor's build phase.
build: false
